use crate::{DesignDocument, DesignElement, CodegenOptions};
use crate::codegen;

pub fn generate_winui_code(document: &DesignDocument, options: &CodegenOptions) -> Result<String, String> {
    let component_name = if options.component_name.is_empty() {
        codegen::to_pascal_case(&document.name)
    } else {
        codegen::to_pascal_case(&options.component_name)
    };

    let mut code = String::new();

    code.push_str(&format!(
        "<!-- WinUI3 XAML for: {} -->\n<!-- Generated by Penpot Desktop -->\n\n",
        component_name
    ));

    code.push_str(&format!(
        "<UserControl\n\
         x:Class=\"PenpotDesign.{}\"\n\
         xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\"\n\
         xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\">\n\n",
        component_name
    ));

    // Use Canvas for proper absolute positioning with Canvas.Left/Top
    code.push_str(&format!(
        "    <Canvas Width=\"{}\" Height=\"{}\" Background=\"#FFFFFF\">\n\n",
        document.width, document.height
    ));

    for element in &document.elements {
        code.push_str(&format!("{}\n", generate_winui_element(element, 3)));
    }

    code.push_str("    </Canvas>\n");
    code.push_str("</UserControl>\n");

    Ok(code)
}

fn generate_winui_element(element: &DesignElement, indent: usize) -> String {
    let ind = "    ".repeat(indent);
    let inner = "    ".repeat(indent + 1);
    let mut xaml = String::new();

    let common_attrs = format!(
        "x:Name=\"{}\"\n\
         {}Canvas.Left=\"{}\"\n\
         {}Canvas.Top=\"{}\"\n\
         {}Width=\"{}\"\n\
         {}Height=\"{}\"\n\
         {}Opacity=\"{}\"\n\
         {}RenderTransformOrigin=\"0.5,0.5\"",
        codegen::to_pascal_case(&element.name),
        ind, element.x,
        ind, element.y,
        ind, element.width,
        ind, element.height,
        ind, element.opacity,
        ind
    );

    match element.element_type.as_str() {
        "text" => {
            if element.rotation != 0.0 {
                xaml.push_str(&format!(
                    "{}<TextBlock\n\
                     {}Text=\"{}\"\n\
                     {}FontSize=\"{}\"\n\
                     {}FontFamily=\"{}\"\n\
                     {}Foreground=\"{}\"\n{}>\n\
                     {}<TextBlock.RenderTransform>\n\
                     {}<RotateTransform Angle=\"{}\" />\n\
                     {}</TextBlock.RenderTransform>\n\
                     {}</TextBlock>",
                    ind, common_attrs,
                    ind, xml_escape(&element.text_content),
                    ind, element.font_size,
                    ind, element.font_family,
                    ind, element.fill_color,
                    ind,
                    inner,
                    inner, element.rotation,
                    inner,
                    ind
                ));
            } else {
                xaml.push_str(&format!(
                    "{}<TextBlock\n\
                     {}Text=\"{}\"\n\
                     {}FontSize=\"{}\"\n\
                     {}FontFamily=\"{}\"\n\
                     {}Foreground=\"{}\"\n\
                     {}/>",
                    ind, common_attrs,
                    ind, xml_escape(&element.text_content),
                    ind, element.font_size,
                    ind, element.font_family,
                    ind, element.fill_color,
                    ind
                ));
            }
        }
        "circle" | "ellipse" => {
            xaml.push_str(&format!(
                "{}<Ellipse\n\
                 {}Fill=\"{}\"\n\
                 {}Stroke=\"{}\"\n\
                 {}StrokeThickness=\"{}\"",
                ind, common_attrs,
                ind, element.fill_color,
                ind, element.stroke_color,
                ind, element.stroke_width
            ));

            if element.rotation != 0.0 {
                xaml.push_str(&format!(
                    "\n{}>\n\
                     {}<Ellipse.RenderTransform>\n\
                     {}<RotateTransform Angle=\"{}\" />\n\
                     {}</Ellipse.RenderTransform>\n\
                     {}</Ellipse>",
                    ind,
                    inner, inner, element.rotation,
                    inner, ind
                ));
            } else {
                xaml.push_str(&format!("\n{}/>", ind));
            }
        }
        "line" => {
            xaml.push_str(&format!(
                "{}<Line\n\
                 {}Fill=\"{}\"\n\
                 {}Stroke=\"{}\"\n\
                 {}StrokeThickness=\"{}\"\n\
                 {}X1=\"0\" Y1=\"0\"\n\
                 {}X2=\"{}\" Y2=\"{}\"\n\
                 {}/>",
                ind, common_attrs,
                ind, element.fill_color,
                ind, element.stroke_color,
                ind, element.stroke_width,
                ind,
                ind, element.width, element.height,
                ind
            ));
        }
        _ => {
            xaml.push_str(&format!(
                "{}<Rectangle\n\
                 {}Fill=\"{}\"\n\
                 {}Stroke=\"{}\"\n\
                 {}StrokeThickness=\"{}\"\n\
                 {}RadiusX=\"{}\"\n\
                 {}RadiusY=\"{}\"",
                ind, common_attrs,
                ind, element.fill_color,
                ind, element.stroke_color,
                ind, element.stroke_width,
                ind, element.border_radius,
                ind, element.border_radius
            ));

            if element.rotation != 0.0 {
                xaml.push_str(&format!(
                    "\n{}>\n\
                     {}<Rectangle.RenderTransform>\n\
                     {}<RotateTransform Angle=\"{}\" />\n\
                     {}</Rectangle.RenderTransform>\n\
                     {}</Rectangle>",
                    ind,
                    inner, inner, element.rotation,
                    inner, ind
                ));
            } else {
                xaml.push_str(&format!("\n{}/>", ind));
            }
        }
    }

    xaml
}

fn xml_escape(text: &str) -> String {
    text
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}
